accum_grad:  4
cmvn_file:  tal_audio/pretrained_models/wenet/cn/global_cmvn
dataset_conf:
    batch_conf:
        batch_size:  8
        batch_type:  static
    fbank_conf:
        dither:  0.1
        frame_length:  25
        frame_shift:  10
        num_mel_bins:  80
    filter_conf:
        max_length:  40960
        min_length:  0
        token_max_length:  200
        token_min_length:  1
    resample_conf:
        resample_rate:  16000
    shuffle:  true
    shuffle_conf:
        shuffle_size:  1500
    sort:  true
    sort_conf:
        sort_size:  500
    spec_aug:  true
    spec_aug_conf:
        max_f:  10
        max_t:  50
        num_f_mask:  2
        num_t_mask:  2
    speed_perturb:  true
decoder:  transformer
decoder_conf:
    attention_heads:  4
    dropout_rate:  0.1
    linear_units:  2048
    num_blocks:  6
    positional_dropout_rate:  0.1
    self_attention_dropout_rate:  0.0
    src_attention_dropout_rate:  0.0
encoder:  conformer
encoder_conf:
    activation_type:  swish
    attention_dropout_rate:  0.0
    attention_heads:  4
    causal:  true
    cnn_module_kernel:  15
    cnn_module_norm:  layer_norm
    dropout_rate:  0.1
    input_layer:  conv2d
    linear_units:  2048
    normalize_before:  true
    num_blocks:  12
    output_size:  256
    pos_enc_layer_type:  rel_pos
    positional_dropout_rate:  0.1
    reverse_att_cnn:  true
    selfattention_layer_type:  rel_selfattn
    use_cnn_module:  true
    use_dynamic_chunk:  true
    use_dynamic_left_chunk:  false
grad_clip:  5
input_dim:  80
is_json_cmvn:  true
log_interval:  100
max_epoch:  180
model_conf:
    ctc_weight:  0.3
    length_normalized_loss:  false
    lsm_weight:  0.1
optim:  adam
optim_conf:
    lr:  0.001
output_dim:  8231
scheduler:  warmuplr
scheduler_conf:
    warmup_steps:  25000
